// T-308 — Playwright config for staging smoke against a real backend.
// T-311 — Run-level X-Session-Id wiring.
//
// Activated by:
//   npm run test:e2e:staging             — manual, caller sets all env vars
//   npm run test:e2e:staging:session     — auto-generates VITE_SESSION_ID if absent
//
// Required env vars (must be set in shell before running):
//   VITE_API_MODE=real
//   VITE_API_BASE_URL=https://api-staging.example.com
//   VITE_API_BEARER_TOKEN=<bearer-token>            (optional — omit header if absent)
//   VITE_SESSION_ID=smoke-<id>                      (optional — auto-generated by staging:session)
//   VITE_FEATURE_SHARING=true                       (required for SMOKE-002 and SMOKE-004)
//
// The Vite dev server inherits VITE_* vars from the shell automatically.
// This config runs critical-real-backend.spec.ts + collaboration-real-backend.spec.ts,
// on port 5174 to avoid conflicts with a running mock-mode dev server on 5173.

import { defineConfig, devices } from '@playwright/test'

const API_BASE = process.env.VITE_API_BASE_URL
const SESSION_ID = process.env.VITE_SESSION_ID

if (!API_BASE) {
  // Warn at config time so the reason is visible in CI logs before any test runs.
  console.warn(
    '\n[staging] VITE_API_BASE_URL is not set.\n' +
    '         Tests will be skipped at runtime.\n' +
    '         To run the smoke:\n' +
    '           VITE_API_MODE=real \\\n' +
    '           VITE_API_BASE_URL=https://api-staging.example.com \\\n' +
    '           VITE_API_BEARER_TOKEN=<token> \\\n' +
    '           npm run test:e2e:staging:session\n',
  )
}

// Log run-level session id at config time — visible in CI logs before test output.
// All HTTP requests in this run will carry X-Session-Id: <SESSION_ID> (via client.ts).
if (SESSION_ID) {
  console.info(`\n[staging] Run session id: ${SESSION_ID}  (X-Session-Id on all HTTP requests)\n`)
} else {
  console.warn(
    '\n[staging] VITE_SESSION_ID is not set — X-Session-Id header will be omitted.\n' +
    '         Use npm run test:e2e:staging:session to auto-generate a run-level id.\n',
  )
}

export default defineConfig({
  testDir: 'tests/e2e',
  testMatch: ['**/critical-real-backend.spec.ts', '**/collaboration-real-backend.spec.ts'],

  // Real API calls are slower than mocks — give each test 3 minutes.
  timeout: 180_000,

  // Assertion timeout: 45s covers slow backend cold-start and LLM generation latency.
  expect: { timeout: 45_000 },

  fullyParallel: false,

  // No retries — staging failures are real failures, not flake.
  retries: 0,

  reporter: process.env.CI ? [['github'], ['list']] : 'list',

  use: {
    baseURL: 'http://localhost:5174',
    viewport: { width: 1280, height: 720 },
    // Always capture trace and video for staging runs — debugging is harder without them.
    trace: 'on',
    video: 'retain-on-failure',
    screenshot: 'only-on-failure',
  },

  projects: [
    {
      name: 'chromium-staging',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  webServer: {
    // Port 5174 avoids conflicts with the default mock-mode dev server on 5173.
    // VITE_* env vars (including API_MODE / BASE_URL / BEARER_TOKEN) are
    // inherited from the shell — Vite picks them up automatically.
    command: 'npm run dev -- --port 5174',
    url: 'http://localhost:5174',
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
  },
})
